import { ServiceItem, StaffTierInfo, WorkerInfo, UserAddress, CouponItem, OrderItem, CommunityGroupBuy } from './types';

export const DEFAULT_USER: UserAddress = {
  id: 'addr_1',
  community: '东达景苑',
  building: '3号楼',
  unit: '2单元',
  room: '501',
  area: 100,
  contactName: '李建国',
  phone: '138 6688 9988',
  isDefault: true,
};

export const COMMUNITIES = [
  '东达景苑',
  '百合馨园',
  '金域蓝湾',
  '和睦家园',
  '阳光水岸',
];

export const SERVICES: ServiceItem[] = [
  {
    id: 'window_cleaning',
    name: '擦玻璃',
    category: 'window',
    tag: '家庭焕新推荐',
    subtitle: '专业人员上门，全屋玻璃双面精擦，窗框窗槽深度清尘',
    iconName: 'Sparkles',
    badge: '物业抵扣专区',
    pricePerUnit: 1.5,
    unit: '㎡',
    calculationType: 'area',
    defaultQuantity: 100,
    highlightBenefit: '东达景苑物业业主立减100元',
    description: '采用专业刮水器与双面磁吸/伸缩擦窗工具，彻底去除水渍、灰尘、鸟粪等顽固污垢，内外透亮。',
    serviceItems: [
      '全屋室内外玻璃双面深度清洁',
      '窗框、窗台表面除尘与擦拭',
      '窗槽死角基础清灰除垢',
      '作业区域地面防水垫铺设及收尾清洁',
    ],
    guarantees: [
      '平台实名与健康认证人员',
      '太平洋商业家政意外险承保',
      '不净重擦，验收后满意再确认',
      '小钥匙物业平台全程售后协调',
    ],
    basePriceCalculation: (area: number) => Math.round(area * 1.5),
  },
  {
    id: 'daily_cleaning',
    name: '家庭保洁',
    category: 'daily',
    tag: '高频日常',
    subtitle: '全屋基础保洁，按小时计费，厨房卫浴客餐厅全覆盖',
    iconName: 'Home',
    badge: '热销保洁',
    pricePerUnit: 40,
    unit: '小时',
    calculationType: 'hourly',
    minQuantity: 2,
    defaultQuantity: 3,
    description: '标准化六区保洁流程：客厅、餐厅、卧室、厨房、卫生间、阳台，自带七色分区专用抹布，杜绝交叉污染。',
    serviceItems: [
      '客厅、卧室台面物品规整与除尘',
      '厨房台面油污擦除及水槽清洁',
      '卫生间台面、镜面、马桶杀菌擦拭',
      '全屋地面吸尘与湿拖打理，垃圾打包',
    ],
    guarantees: [
      '持健康证上岗，实名认证',
      '严格执行七色分区保洁毛巾标准',
      '超时不加价，不向老人索要小费',
      '损坏照价赔偿，平台直赔先行',
    ],
    basePriceCalculation: (hours: number) => hours * 40,
  },
  {
    id: 'range_hood',
    name: '洗油烟机',
    category: 'appliance',
    tag: '除油首选',
    subtitle: '高温高压蒸汽深度除油，免拆机不伤内部结构',
    iconName: 'Flame',
    badge: '好评如潮',
    pricePerUnit: 138,
    unit: '台',
    calculationType: 'fixed',
    defaultQuantity: 1,
    description: '采用140℃高温脉冲蒸汽发生器与环保食品级除油剂，强力瓦解风轮、油网、滤网顽固油垢，还原厨房清新。',
    serviceItems: [
      '灶台、橱柜全方位专业防护罩铺设',
      '油网、油盒、外壳深度除油清洗',
      '风轮及腔体140℃高温蒸汽深度灭菌',
      '装机调试、测试吸力，清理现场油污',
    ],
    guarantees: [
      '清洗后原位复原，保证正常运行',
      '无隐形增项，不推销清洗剂',
      '油污带走，灶台台面亮洁如新',
    ],
    basePriceCalculation: (qty: number) => qty * 138,
  },
  {
    id: 'appliance_cleaning',
    name: '家电清洗',
    category: 'appliance',
    tag: '健康除螨',
    subtitle: '空调挂机/柜机、洗衣机内筒、热水器除垢杀菌',
    iconName: 'Wind',
    pricePerUnit: 99,
    unit: '台起',
    calculationType: 'fixed',
    defaultQuantity: 1,
    description: '涵盖挂机空调、柜机空调、波轮/滚筒洗衣机、电热水器深度拆洗除菌除异味，守护中老年呼吸与皮肤健康。',
    serviceItems: [
      '空调过滤网、蒸发器翅片深层杀菌',
      '洗衣机内外筒夹层污垢生物酶降解清洗',
      '热水器内胆水垢冲刷与镁棒检查',
      '紫外线/臭氧全套消毒收尾',
    ],
    guarantees: [
      '专业家电清洗技师上门',
      '专用防水防尘罩，保护墙面地板',
      '清洗完成现场通电验收测试',
    ],
    basePriceCalculation: (qty: number) => qty * 99,
  },
  {
    id: 'plumbing_repair',
    name: '疏通维修',
    category: 'plumbing',
    tag: '快速上门',
    subtitle: '马桶/地漏/厨房下水疏通，龙头水阀漏水快修',
    iconName: 'Wrench',
    badge: '30分钟响应',
    pricePerUnit: 68,
    unit: '次起',
    calculationType: 'fixed',
    defaultQuantity: 1,
    description: '社区周边驻点老师傅快速响应，专业电动管道疏通机、高压气炮，明码标价，不通不收费。',
    serviceItems: [
      '马桶堵塞、蹲坑、主管道快速排堵疏通',
      '厨房菜盆、卫生间地漏毛发油污清理',
      '水龙头、三角阀老化断丝取出与更换',
      '测试下水通畅度，清理残留泥污',
    ],
    guarantees: [
      '疏通成功后通水测试满意再付款',
      '明码标价，维修前先报总价',
      '疏通质保30天，堵塞免费复查',
    ],
    basePriceCalculation: (qty: number) => qty * 68,
  },
  {
    id: 'deep_cleaning',
    name: '深度保洁',
    category: 'deep',
    tag: '大扫除/开荒',
    subtitle: '年度大扫除、全屋死角深度除垢、新居入住焕新',
    iconName: 'Layers',
    pricePerUnit: 4.5,
    unit: '㎡',
    calculationType: 'area',
    defaultQuantity: 100,
    description: '双人组或三人组专业保洁团队上门，包含全屋顶棚立面、踢脚线、门窗、柜体内外全方位深度除尘去渍。',
    serviceItems: [
      '全屋立面墙顶除尘除蛛网',
      '玻璃双面精擦、窗框彻底吸尘清垢',
      '厨房重油污深度瓦解，瓷砖墙缝清洁',
      '卫生间洁具水垢、水渍、黑斑高温蒸汽清洁',
    ],
    guarantees: [
      '团队化作业，全套专业商用设备',
      '业主现场逐项验单无误后再离开',
      '物业驻点监督，售后保障无忧',
    ],
    basePriceCalculation: (area: number) => Math.round(area * 4.5),
  },
];

export const STAFF_TIERS: StaffTierInfo[] = [
  {
    tier: 'standard',
    title: '标准服务',
    badge: '经济实惠',
    priceDiff: 0,
    features: [
      '通过平台实名认证与健康核验',
      '严格执行标准化家庭作业规范',
      '配备基础清洁与维护工具箱',
      '性价比高，适合日常维护',
    ],
  },
  {
    tier: 'skilled',
    title: '熟练服务',
    badge: '小区邻居首选 · 推荐',
    priceDiff: 0,
    recommended: true,
    features: [
      '从业经验3年以上，服务超200户',
      '熟悉东达景苑各户型窗型结构',
      '工作流程娴熟，细节死角处理更完善',
      '好评率高于98%，沟通亲和有耐心',
    ],
  },
  {
    tier: 'premium',
    title: '品质服务',
    badge: '金牌匠心',
    priceDiff: 20,
    features: [
      '从业5年以上资深技师，综合评分4.95+',
      '配备高端进口无痕刮条与高压蒸汽机',
      '特别强化中老年长辈沟通关怀流程',
      '赠送门窗滑轨养护与五金润滑检测',
    ],
  },
];

export const WORKERS: WorkerInfo[] = [
  {
    id: 'worker_1',
    name: '王建华（王师傅）',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    gender: '男',
    experienceYears: 8,
    servedHouseholds: 326,
    rating: 4.9,
    skills: ['擦玻璃专家', '家电深度清洗', '管道疏通'],
    certifications: {
      realName: true,
      healthCert: true,
      insurance: true,
      noCriminalRecord: true,
      skillCert: true,
    },
    phone: '139 8888 7766',
    bio: '退役军人转家政技师，常年在东达景苑及周边社区服务，干活仔细利索，工具收拾干净，深受长辈邻居信赖。',
  },
  {
    id: 'worker_2',
    name: '张桂芳（张阿姨）',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    gender: '女',
    experienceYears: 6,
    servedHouseholds: 280,
    rating: 4.95,
    skills: ['日常精细保洁', '厨房重油污', '衣物收纳'],
    certifications: {
      realName: true,
      healthCert: true,
      insurance: true,
      noCriminalRecord: true,
      skillCert: true,
    },
    phone: '136 6677 8899',
    bio: '金牌家政员，干活麻利不偷懒，自备7色分区无菌毛巾，说话轻柔有礼貌。',
  },
  {
    id: 'worker_3',
    name: '刘志刚（刘师傅）',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    gender: '男',
    experienceYears: 10,
    servedHouseholds: 410,
    rating: 4.88,
    skills: ['油烟机免拆蒸汽洗', '空调高温消杀', '水电微修'],
    certifications: {
      realName: true,
      healthCert: true,
      insurance: true,
      noCriminalRecord: true,
      skillCert: true,
    },
    phone: '135 1234 5678',
    bio: '持有高级家电清洗资质与电工证，工具齐全，对各种老旧型号油烟机和空调了如指掌。',
  },
];

export const INITIAL_COUPONS: CouponItem[] = [
  {
    id: 'coupon_renewal_100',
    title: '100元家庭焕新优惠券',
    amount: 100,
    minSpend: 100,
    source: '东达景苑2026年度物业缴费活动专享',
    applicableCategory: 'window',
    validUntil: '2026-12-31',
    status: 'available',
    description: '东达景苑物业年度感恩回馈，凭券预约全屋擦玻璃直减100元现金',
  },
  {
    id: 'coupon_general_20',
    title: '20元邻里生活体验券',
    amount: 20,
    minSpend: 60,
    source: '为您服务小钥匙新人入驻礼',
    applicableCategory: 'all',
    validUntil: '2026-12-31',
    status: 'available',
    description: '全场家政保洁、家电清洗、管道疏通通用立减',
  },
  {
    id: 'coupon_appliance_30',
    title: '30元油烟机清洗特惠券',
    amount: 30,
    minSpend: 130,
    source: '春季换季健康家电清洗节',
    applicableCategory: 'appliance',
    validUntil: '2026-11-30',
    status: 'available',
    description: '仅限洗油烟机与家电清洗服务下单使用',
  },
  {
    id: 'coupon_used_1',
    title: '15元日常保洁体验券',
    amount: 15,
    minSpend: 50,
    source: '社区便民日赠送',
    applicableCategory: 'daily',
    validUntil: '2026-08-01',
    status: 'used',
    description: '已于2026-07-28家庭保洁订单使用抵扣',
  },
];

export const INITIAL_ORDERS: OrderItem[] = [
  {
    id: 'order_1001',
    orderNumber: 'JZ20261028001',
    serviceId: 'window_cleaning',
    serviceName: '家庭焕新·擦玻璃',
    category: 'window',
    tier: 'skilled',
    tierTitle: '熟练服务',
    address: DEFAULT_USER,
    quantity: 100,
    unit: '㎡',
    scheduledTime: '10月28日上午 (09:00 - 11:30)',
    originalPrice: 150,
    discountAmount: 100,
    appliedCouponId: 'coupon_renewal_100',
    finalPrice: 50,
    status: 'pending_arrival',
    worker: WORKERS[0],
    createdAt: '2026-10-25 14:32',
    payMethod: 'renewal_benefit',
  },
  {
    id: 'order_1002',
    orderNumber: 'JZ20261015088',
    serviceId: 'daily_cleaning',
    serviceName: '家庭保洁',
    category: 'daily',
    tier: 'standard',
    tierTitle: '标准服务',
    address: DEFAULT_USER,
    quantity: 3,
    unit: '小时',
    scheduledTime: '10月15日下午 (14:00 - 17:00)',
    originalPrice: 120,
    discountAmount: 20,
    appliedCouponId: 'coupon_general_20',
    finalPrice: 100,
    status: 'completed',
    worker: WORKERS[1],
    createdAt: '2026-10-14 09:15',
    payMethod: 'wechat',
    hasReviewed: true,
    reviewData: {
      satisfaction: 'satisfied',
      tags: ['干得干净', '服务态度好', '准时', '工具专业'],
      comment: '张阿姨干活真认真，窗台厨房擦得锃亮，很有耐心！',
      createdAt: '2026-10-15 17:30',
    },
  },
];

export const COMMUNITY_GROUP_BUY: CommunityGroupBuy = {
  communityName: '东达景苑',
  serviceName: '全屋擦玻璃社区集中团购',
  targetServiceId: 'window_cleaning',
  joinedHouseholds: 8,
  nextTierHouseholds: 10,
  currentDiscount: 0.95,
  nextDiscount: 0.90,
  deadline: '2026-11-15',
};

export const HOTLINE_NUMBER = '400-820-9966';
export const PROPERTY_DESK_PHONE = '0571-88996600';
